name: First Worflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: unbuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World"
      - name: Print goodbye
        run: "Done - bye!"
